import { Correspondence, DashboardStats, User } from '@/types';

// Mock data
export const mockUsers: User[] = [
  { id: '1', name: 'أحمد محمد', email: 'ahmed@example.com', role: 'admin', department: 'IT' },
  { id: '2', name: 'فاطمة علي', email: 'fatima@example.com', role: 'general_manager', department: 'Management' },
  { id: '3', name: 'خالد سعيد', email: 'khaled@example.com', role: 'department_manager', department: 'HR' },
  { id: '4', name: 'سارة أحمد', email: 'sara@example.com', role: 'writer', department: 'Admin' },
];

export const mockCorrespondence: Correspondence[] = [
  // Incoming
  {
    id: '1',
    type: 'incoming',
    title: 'تسديد فاتورة السيرفر',
    topic: 'تسديد فاتورة السيرفر',
    description: 'طلب تسديد فاتورة السيرفر للشهر الحالي',
    fileName: 'فاتورة_السيرفر_يناير_2025.pdf',
    fileType: 'pdf',
    fileSize: 245760,
    sender: 'شركة الاستضافة',
    department: 'IT',
    priority: 'high',
    status: 'pending',
    date: new Date('2025-01-25'),
    documentNumber: 'IN-2025-001',
    serialNumber: 'IN-2025-001',
    attachments: ['فاتورة_السيرفر_يناير_2025.pdf'],
    createdBy: '1',
    createdAt: new Date('2025-01-25'),
    updatedAt: new Date('2025-01-25'),
  },
  {
    id: '4',
    type: 'incoming',
    title: 'إشعار من الهيئة العامة للضرائب',
    content: 'طلب تقديم الوثائق المالية للعام المالي 2024',
    sender: 'الهيئة العامة للضرائب',
    priority: 'urgent',
    status: 'in_review',
    date: new Date('2025-01-18'),
    serialNumber: 'IN-2025-002',
    createdBy: '1',
    createdAt: new Date('2025-01-18'),
    updatedAt: new Date('2025-01-18'),
  },
  {
    id: '5',
    type: 'incoming',
    title: 'دعوة لحضور ورشة عمل',
    content: 'دعوة رسمية لحضور ورشة عمل حول التطوير الإداري والرقمنة',
    sender: 'معهد التطوير الإداري',
    priority: 'medium',
    status: 'pending',
    date: new Date('2025-01-20'),
    serialNumber: 'IN-2025-003',
    createdBy: '1',
    createdAt: new Date('2025-01-20'),
    updatedAt: new Date('2025-01-20'),
  },
  {
    id: '6',
    type: 'incoming',
    title: 'طلب عروض أسعار',
    content: 'طلب تقديم عروض أسعار لتوريد أجهزة حاسوب ومعدات مكتبية',
    sender: 'شركة التقنية المتقدمة',
    priority: 'high',
    status: 'in_review',
    date: new Date('2025-01-22'),
    serialNumber: 'IN-2025-004',
    createdBy: '1',
    createdAt: new Date('2025-01-22'),
    updatedAt: new Date('2025-01-22'),
  },
  {
    id: '7',
    type: 'incoming',
    title: 'مراسلة من البنك المركزي',
    content: 'تحديثات على اللوائح المالية الجديدة المتعلقة بالمعاملات المصرفية',
    sender: 'البنك المركزي',
    priority: 'urgent',
    status: 'pending',
    date: new Date('2025-01-25'),
    serialNumber: 'IN-2025-005',
    createdBy: '1',
    createdAt: new Date('2025-01-25'),
    updatedAt: new Date('2025-01-25'),
  },
  {
    id: '8',
    type: 'incoming',
    title: 'إشعار تجديد الرخصة',
    content: 'إشعار بموعد تجديد الرخصة التجارية للعام 2025',
    sender: 'وزارة التجارة والصناعة',
    priority: 'medium',
    status: 'completed',
    date: new Date('2025-01-10'),
    serialNumber: 'IN-2025-006',
    createdBy: '1',
    createdAt: new Date('2025-01-10'),
    updatedAt: new Date('2025-01-12'),
  },
  {
    id: '9',
    type: 'incoming',
    title: 'طلب معلومات من هيئة المواصفات',
    content: 'طلب تقديم معلومات عن المنتجات والخدمات المقدمة',
    sender: 'هيئة المواصفات والمقاييس',
    priority: 'low',
    status: 'archived',
    date: new Date('2024-12-28'),
    serialNumber: 'IN-2024-045',
    createdBy: '1',
    createdAt: new Date('2024-12-28'),
    updatedAt: new Date('2025-01-05'),
  },
  {
    id: '10',
    type: 'incoming',
    title: 'دعوة للمشاركة في معرض',
    content: 'دعوة رسمية للمشاركة في المعرض السنوي للتكنولوجيا والابتكار',
    sender: 'غرفة التجارة والصناعة',
    priority: 'medium',
    status: 'in_review',
    date: new Date('2025-01-23'),
    serialNumber: 'IN-2025-007',
    createdBy: '1',
    createdAt: new Date('2025-01-23'),
    updatedAt: new Date('2025-01-23'),
  },
  // Outgoing
  {
    id: '2',
    type: 'outgoing',
    title: 'رد على المراسلة الواردة من وزارة التربية',
    content: 'نرفق المعلومات المطلوبة عن المشروع الجديد مع الوثائق المرفقة',
    recipient: 'وزارة التربية والتعليم',
    priority: 'medium',
    status: 'completed',
    date: new Date('2025-01-16'),
    serialNumber: 'OUT-2025-001',
    createdBy: '2',
    createdAt: new Date('2025-01-16'),
    updatedAt: new Date('2025-01-16'),
  },
  {
    id: '11',
    type: 'outgoing',
    title: 'طلب دعم مالي للمشروع',
    content: 'طلب تمويل للمشروع الجديد من صندوق التنمية الصناعية',
    recipient: 'صندوق التنمية الصناعية',
    priority: 'high',
    status: 'pending',
    date: new Date('2025-01-19'),
    serialNumber: 'OUT-2025-002',
    createdBy: '2',
    createdAt: new Date('2025-01-19'),
    updatedAt: new Date('2025-01-19'),
  },
  {
    id: '12',
    type: 'outgoing',
    title: 'تقديم عرض أسعار',
    content: 'تقديم عرض أسعار لتوريد الخدمات التقنية والمعدات المطلوبة',
    recipient: 'شركة النفط الوطنية',
    priority: 'high',
    status: 'in_review',
    date: new Date('2025-01-21'),
    serialNumber: 'OUT-2025-003',
    createdBy: '2',
    createdAt: new Date('2025-01-21'),
    updatedAt: new Date('2025-01-21'),
  },
  {
    id: '13',
    type: 'outgoing',
    title: 'شكر وتقدير',
    content: 'رسالة شكر وتقدير للجهود المبذولة في إنجاح المؤتمر السنوي',
    recipient: 'اللجنة المنظمة للمؤتمر',
    priority: 'low',
    status: 'completed',
    date: new Date('2025-01-14'),
    serialNumber: 'OUT-2025-004',
    createdBy: '2',
    createdAt: new Date('2025-01-14'),
    updatedAt: new Date('2025-01-14'),
  },
  {
    id: '14',
    type: 'outgoing',
    title: 'طلب موافقة على التصميم',
    content: 'طلب الموافقة على التصميم النهائي للمشروع قبل البدء في التنفيذ',
    recipient: 'إدارة المشاريع',
    priority: 'urgent',
    status: 'pending',
    date: new Date('2025-01-24'),
    serialNumber: 'OUT-2025-005',
    createdBy: '2',
    createdAt: new Date('2025-01-24'),
    updatedAt: new Date('2025-01-24'),
  },
  {
    id: '15',
    type: 'outgoing',
    title: 'إشعار تغيير العنوان',
    content: 'إشعار رسمي بتغيير العنوان الجديد للمؤسسة',
    recipient: 'جميع الجهات المعنية',
    priority: 'medium',
    status: 'completed',
    date: new Date('2025-01-08'),
    serialNumber: 'OUT-2025-006',
    createdBy: '2',
    createdAt: new Date('2025-01-08'),
    updatedAt: new Date('2025-01-08'),
  },
  {
    id: '16',
    type: 'outgoing',
    title: 'طلب تجديد العقد',
    content: 'طلب تجديد عقد الخدمات مع الشركة الشريكة',
    recipient: 'شركة الخدمات المتكاملة',
    priority: 'high',
    status: 'in_review',
    date: new Date('2025-01-26'),
    serialNumber: 'OUT-2025-007',
    createdBy: '2',
    createdAt: new Date('2025-01-26'),
    updatedAt: new Date('2025-01-26'),
  },
  {
    id: '17',
    type: 'outgoing',
    title: 'تقرير الأداء الشهري',
    content: 'إرسال تقرير الأداء الشهري لشهر يناير 2025',
    recipient: 'المجلس الإداري',
    priority: 'medium',
    status: 'archived',
    date: new Date('2025-01-01'),
    serialNumber: 'OUT-2025-008',
    createdBy: '2',
    createdAt: new Date('2025-01-01'),
    updatedAt: new Date('2025-01-02'),
  },
  // Internal
  {
    id: '3',
    type: 'internal',
    title: 'ارسال تقرير عن الإدارة',
    topic: 'ارسال تقرير عن الإدارة',
    description: 'طلب إرسال تقرير شامل عن أداء الإدارة للربع الأول',
    fileName: 'تقرير_الإدارة_الربع_الأول.xlsx',
    fileType: 'excel',
    fileSize: 512000,
    department: 'Management',
    priority: 'urgent',
    status: 'in_review',
    date: new Date('2025-01-25'),
    documentNumber: 'INT-2025-001',
    attachments: ['تقرير_الإدارة_الربع_الأول.xlsx'],
    createdBy: '3',
    createdAt: new Date('2025-01-25'),
    updatedAt: new Date('2025-01-25'),
  },
  {
    id: '18',
    type: 'internal',
    title: 'طلب اجتماع طارئ',
    content: 'طلب عقد اجتماع طارئ لمناقشة التحديات الحالية في المشروع',
    department: 'Management',
    priority: 'urgent',
    status: 'pending',
    date: new Date('2025-01-27'),
    createdBy: '3',
    createdAt: new Date('2025-01-27'),
    updatedAt: new Date('2025-01-27'),
  },
  {
    id: '19',
    type: 'internal',
    title: 'تقيم الموظفيين عندكم',
    topic: 'تقيم الموظفيين عندكم',
    description: 'طلب تقييم أداء الموظفين في القسم',
    fileName: 'تقييم_الموظفين_2025.docx',
    fileType: 'word',
    fileSize: 128000,
    department: 'HR',
    priority: 'high',
    status: 'in_review',
    date: new Date('2025-01-25'),
    documentNumber: 'INT-2025-002',
    attachments: ['تقييم_الموظفين_2025.docx'],
    createdBy: '4',
    createdAt: new Date('2025-01-25'),
    updatedAt: new Date('2025-01-25'),
  },
  {
    id: '20',
    type: 'internal',
    title: 'تقرير الأسبوعي',
    content: 'إرسال التقرير الأسبوعي عن سير العمل في القسم',
    department: 'IT',
    priority: 'low',
    status: 'completed',
    date: new Date('2025-01-24'),
    createdBy: '4',
    createdAt: new Date('2025-01-24'),
    updatedAt: new Date('2025-01-24'),
  },
  {
    id: '21',
    type: 'internal',
    title: 'طلب دعم تقني',
    content: 'طلب دعم تقني من إدارة تقنية المعلومات لحل مشكلة في النظام',
    department: 'IT',
    priority: 'high',
    status: 'replied',
    date: new Date('2025-01-23'),
    createdBy: '1',
    createdAt: new Date('2025-01-23'),
    updatedAt: new Date('2025-01-23'),
  },
  {
    id: '22',
    type: 'internal',
    title: 'إشعار اجتماع دوري',
    content: 'إشعار بعقد الاجتماع الدوري الشهري لجميع الإدارات',
    department: 'Admin',
    priority: 'medium',
    status: 'completed',
    date: new Date('2025-01-22'),
    createdBy: '4',
    createdAt: new Date('2025-01-22'),
    updatedAt: new Date('2025-01-22'),
  },
  {
    id: '23',
    type: 'internal',
    title: 'طلب إجازة جماعية',
    content: 'طلب موافقة على إجازة جماعية لفريق العمل',
    department: 'HR',
    priority: 'medium',
    status: 'in_review',
    date: new Date('2025-01-26'),
    createdBy: '3',
    createdAt: new Date('2025-01-26'),
    updatedAt: new Date('2025-01-26'),
  },
  {
    id: '24',
    type: 'internal',
    title: 'تحديث السياسات',
    content: 'إشعار بتحديث السياسات الداخلية للمؤسسة',
    department: 'Management',
    priority: 'high',
    status: 'archived',
    date: new Date('2025-01-05'),
    createdBy: '2',
    createdAt: new Date('2025-01-05'),
    updatedAt: new Date('2025-01-06'),
  },
  {
    id: '25',
    type: 'internal',
    title: 'طلب معدات جديدة',
    content: 'طلب توفير معدات وأجهزة جديدة للقسم',
    department: 'IT',
    priority: 'medium',
    status: 'pending',
    date: new Date('2025-01-28'),
    createdBy: '1',
    createdAt: new Date('2025-01-28'),
    updatedAt: new Date('2025-01-28'),
  },
  {
    id: '26',
    type: 'internal',
    title: 'تقرير التدريب',
    content: 'تقرير عن برامج التدريب المنفذة خلال الشهر',
    department: 'HR',
    priority: 'low',
    status: 'completed',
    date: new Date('2025-01-20'),
    createdBy: '3',
    createdAt: new Date('2025-01-20'),
    updatedAt: new Date('2025-01-20'),
  },
  // More archived documents
  {
    id: '27',
    type: 'incoming',
    title: 'عقد توريد معدات 2024',
    topic: 'عقد توريد معدات 2024',
    description: 'عقد توريد المعدات التقنية للعام 2024',
    fileName: 'عقد_توريد_معدات_2024.pdf',
    fileType: 'pdf',
    fileSize: 1024000,
    sender: 'شركة المعدات التقنية',
    department: 'IT',
    priority: 'medium',
    status: 'archived',
    date: new Date('2024-11-15'),
    documentNumber: 'IN-2024-050',
    serialNumber: 'IN-2024-050',
    attachments: ['عقد_توريد_معدات_2024.pdf'],
    createdBy: '1',
    createdAt: new Date('2024-11-15'),
    updatedAt: new Date('2024-12-01'),
  },
  {
    id: '28',
    type: 'outgoing',
    title: 'تقرير سنوي 2024',
    topic: 'تقرير سنوي 2024',
    description: 'التقرير السنوي الشامل لأنشطة المؤسسة لعام 2024',
    fileName: 'التقرير_السنوي_2024.pdf',
    fileType: 'pdf',
    fileSize: 2048000,
    recipient: 'المجلس الإداري',
    department: 'Management',
    priority: 'high',
    status: 'archived',
    date: new Date('2024-12-31'),
    documentNumber: 'OUT-2024-100',
    serialNumber: 'OUT-2024-100',
    attachments: ['التقرير_السنوي_2024.pdf'],
    createdBy: '2',
    createdAt: new Date('2024-12-31'),
    updatedAt: new Date('2025-01-10'),
  },
  {
    id: '29',
    type: 'internal',
    title: 'سياسة الأمن السيبراني',
    topic: 'سياسة الأمن السيبراني',
    description: 'السياسة المحدثة للأمن السيبراني وحماية البيانات',
    fileName: 'سياسة_الأمن_السيبراني_2024.pdf',
    fileType: 'pdf',
    fileSize: 512000,
    department: 'IT',
    priority: 'high',
    status: 'archived',
    date: new Date('2024-10-20'),
    documentNumber: 'INT-2024-030',
    attachments: ['سياسة_الأمن_السيبراني_2024.pdf'],
    createdBy: '1',
    createdAt: new Date('2024-10-20'),
    updatedAt: new Date('2024-11-01'),
  },
  {
    id: '30',
    type: 'incoming',
    title: 'فاتورة خدمات شهر ديسمبر 2024',
    topic: 'فاتورة خدمات شهر ديسمبر 2024',
    description: 'فاتورة الخدمات الشهرية لشهر ديسمبر 2024',
    fileName: 'فاتورة_ديسمبر_2024.pdf',
    fileType: 'pdf',
    fileSize: 256000,
    sender: 'شركة الخدمات العامة',
    department: 'Finance',
    priority: 'medium',
    status: 'archived',
    date: new Date('2024-12-15'),
    documentNumber: 'IN-2024-055',
    serialNumber: 'IN-2024-055',
    attachments: ['فاتورة_ديسمبر_2024.pdf'],
    createdBy: '1',
    createdAt: new Date('2024-12-15'),
    updatedAt: new Date('2024-12-20'),
  },
  {
    id: '31',
    type: 'outgoing',
    title: 'خطاب شكر وتقدير',
    topic: 'خطاب شكر وتقدير',
    description: 'خطاب شكر وتقدير للشركاء الاستراتيجيين',
    fileName: 'خطاب_شكر_وتقدير_2024.pdf',
    fileType: 'pdf',
    fileSize: 128000,
    recipient: 'الشركاء الاستراتيجيون',
    department: 'Management',
    priority: 'low',
    status: 'archived',
    date: new Date('2024-12-20'),
    documentNumber: 'OUT-2024-105',
    serialNumber: 'OUT-2024-105',
    attachments: ['خطاب_شكر_وتقدير_2024.pdf'],
    createdBy: '2',
    createdAt: new Date('2024-12-20'),
    updatedAt: new Date('2024-12-25'),
  },
  {
    id: '32',
    type: 'internal',
    title: 'دليل الموظف الجديد',
    topic: 'دليل الموظف الجديد',
    description: 'الدليل الشامل للموظفين الجدد',
    fileName: 'دليل_الموظف_الجديد_2024.pdf',
    fileType: 'pdf',
    fileSize: 768000,
    department: 'HR',
    priority: 'medium',
    status: 'archived',
    date: new Date('2024-09-10'),
    documentNumber: 'INT-2024-025',
    attachments: ['دليل_الموظف_الجديد_2024.pdf'],
    createdBy: '3',
    createdAt: new Date('2024-09-10'),
    updatedAt: new Date('2024-10-01'),
  },
  {
    id: '33',
    type: 'incoming',
    title: 'شهادة ISO 9001',
    topic: 'شهادة ISO 9001',
    description: 'شهادة الجودة ISO 9001:2015',
    fileName: 'شهادة_ISO_9001_2024.pdf',
    fileType: 'pdf',
    fileSize: 384000,
    sender: 'هيئة التقييس الدولية',
    department: 'Admin',
    priority: 'high',
    status: 'archived',
    date: new Date('2024-08-05'),
    documentNumber: 'IN-2024-040',
    serialNumber: 'IN-2024-040',
    attachments: ['شهادة_ISO_9001_2024.pdf'],
    createdBy: '1',
    createdAt: new Date('2024-08-05'),
    updatedAt: new Date('2024-08-10'),
  },
  {
    id: '34',
    type: 'outgoing',
    title: 'عرض تقديمي للمستثمرين',
    topic: 'عرض تقديمي للمستثمرين',
    description: 'عرض تقديمي شامل للمستثمرين المحتملين',
    fileName: 'عرض_تقديمي_المستثمرين_2024.pdf',
    fileType: 'pdf',
    fileSize: 1536000,
    recipient: 'المستثمرون',
    department: 'Management',
    priority: 'high',
    status: 'archived',
    date: new Date('2024-11-30'),
    documentNumber: 'OUT-2024-095',
    serialNumber: 'OUT-2024-095',
    attachments: ['عرض_تقديمي_المستثمرين_2024.pdf'],
    createdBy: '2',
    createdAt: new Date('2024-11-30'),
    updatedAt: new Date('2024-12-05'),
  },
  {
    id: '35',
    type: 'internal',
    title: 'تقرير التدريب السنوي',
    topic: 'تقرير التدريب السنوي',
    description: 'تقرير شامل عن برامج التدريب لعام 2024',
    fileName: 'تقرير_التدريب_السنوي_2024.pdf',
    fileType: 'pdf',
    fileSize: 640000,
    department: 'HR',
    priority: 'medium',
    status: 'archived',
    date: new Date('2024-12-28'),
    documentNumber: 'INT-2024-035',
    attachments: ['تقرير_التدريب_السنوي_2024.pdf'],
    createdBy: '3',
    createdAt: new Date('2024-12-28'),
    updatedAt: new Date('2025-01-05'),
  },
  {
    id: '36',
    type: 'incoming',
    title: 'عقد صيانة سنوي',
    topic: 'عقد صيانة سنوي',
    description: 'عقد صيانة المعدات والأنظمة للعام 2024',
    fileName: 'عقد_صيانة_سنوي_2024.pdf',
    fileType: 'pdf',
    fileSize: 896000,
    sender: 'شركة الصيانة المتخصصة',
    department: 'IT',
    priority: 'medium',
    status: 'archived',
    date: new Date('2024-07-15'),
    documentNumber: 'IN-2024-035',
    serialNumber: 'IN-2024-035',
    attachments: ['عقد_صيانة_سنوي_2024.pdf'],
    createdBy: '1',
    createdAt: new Date('2024-07-15'),
    updatedAt: new Date('2024-08-01'),
  },
];

export const getDashboardStats = (): DashboardStats => {
  const incoming = mockCorrespondence.filter(c => c.type === 'incoming').length;
  const outgoing = mockCorrespondence.filter(c => c.type === 'outgoing').length;
  const internal = mockCorrespondence.filter(c => c.type === 'internal').length;
  const archived = mockCorrespondence.filter(c => c.status === 'archived').length;
  const urgent = mockCorrespondence.filter(c => c.priority === 'urgent').length;
  const pending = mockCorrespondence.filter(c => c.status === 'pending').length;

  return { incoming, outgoing, internal, archived, urgent, pending };
};
